channels:
  active: both
  telegram:
    allowed_username: '*'
    enabled: true
  whatsapp:
    enabled: true
    allow_from: ["*"] # Change to ["123456789"] to restrict access
llm:
  default_provider: groq
  model_name: llama-3.3-70b-versatile
memory:
  chunk_size: 500
  short_term_max_messages: 20
  vector_db_path: ./chroma_db
tools:
  task_planning: true
  tool_calling: true
